### ISSUE TITLE
not all log backups included

### ISSUE THREAD

**Issue by mcbroe** [XML400/RestoreGene#3]
Hi,
i am just testing your great script and found something. Maybe a bug, or something i don't understand.
I have a small testdb on a 2014 MS SQL Server and using o hallengren script to create the backups.
In the first screenshot there are the taken backups in my test period. the second screenshot shows the restore script from RestoreGene version 4. Why are there only 3 log Backups to restore?

Thanks
![backupfiles](https://cloud.githubusercontent.com/assets/14178934/9734227/9bbf6fc6-5631-11e5-9d74-dc2feae128dd.png)
![restorescript](https://cloud.githubusercontent.com/assets/14178934/9734228/9bd1bd70-5631-11e5-8964-276904ec8cef.png)

**Comment by PabloBrewster** [comment]
Hi,
Did the restore script work? Looking at it very quickly, is the diff backup last lsn the same as the missing log backup lsn ?
Thanks and regards
Paul

**Comment by mcbroe** [comment]
Yes, the restore worked. And the LastLSN from the diff backup is identical to the LastLSN of the missing log Backup.
Does that mean, no data in the backup, so it is not needed to restore? Would be great if you can confirm that.

I am just starting as DBA,  sorry for this beginner question.

And thanks for this great script!

best regards
Sebastian

**Comment by PabloBrewster** [comment]
Hi,
There were no logged transactions between the end of the differential backup and the end of the log backup so the log backup isn't needed. The LSN checks are fairly new in the script, previously this log backup would have been included (based on backup finish date time) but it's not needed.

Thanks for the positive feedback, good luck and best wishes.
Paul

**Comment by mcbroe** [comment]
Thx
